---
output:
  pdf_document:
    includes:
      before_body: title.sty
    keep_tex: TRUE
    number_sections: TRUE
fontsize: 12pt
geometry: "left=1in,right=1in,top=1in,bottom=1in"
urlcolor: blue
header-includes:
- \usepackage{sectsty}
- \usepackage{setspace}\spacing{1}
- \usepackage{float}
- \usepackage{fancyhdr}
- \usepackage{mathtools}
- \usepackage{algorithm,algpseudocode,caption}
- \usepackage{natbib}\bibliographystyle{apalike}
- \usepackage[nottoc, numbib]{tocbibind}
- \usepackage{paralist}
- \usepackage{verbatim}
- \usepackage{comment}
- \usepackage{soul}
- \usepackage{array}
bibliography: dissertationbibliography.bib
biblio-style: apalike
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      # eval = FALSE,
                      comment = NA, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.pos = 'H', 
                      fig.align = 'center', 
                      fig.height = 3, 
                      fig.width = 5, 
                      fig.dpi = 300)
op = function(x, d=2) sprintf(paste0("%1.",d,"f"), x) #allows display of decimal control
```


<!-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% Sections %%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
\pagenumbering{arabic}

```{r intro, child = 'sections/Sec1-Introduction/introduction.Rmd'}
```

```{r litreview, child = 'sections/Sec2-LitReview/litreview.Rmd'}
```

```{r BLRCRmodel, child = 'sections/Sec3-BLRCRmodel/BLRCRmain.Rmd'}
```

```{r selectcovariates, child = 'sections/Sec4-CovariateDistribution/selectcovariates.Rmd'}
```

```{r hiddencovariates, child = 'sections/Sec5-UnobservedHeterogeneity/hiddencovariates.Rmd'}
```

```{r modelselection, child = 'sections/Sec6-ModelSelection/modelselection.Rmd'}
```

```{r example1, child = 'sections/Sec7-Example1/example1.Rmd'}
```

```{r example2, child = 'sections/Sec8-Example2/example2.Rmd'}
```

```{r conclusion, child = 'sections/Sec9-Conclusion/conclusion.Rmd'}
```

\newpage

```{r appendix, child = 'sections/Appendix/appendix.Rmd'}
```

\newpage

```{r biblio, child = 'sections/References/references.Rmd'}
```

\newpage
```{r curriculumvitae, child = 'sections/CV/curriculumvitae.Rmd'}
```

