---
title: ''
output: pdf_document
---

\subsection{Conditional Independence and Unobserved Heterogeneity}
\label{Sec:condindependence}


The model construction of section \ref{sec:CRwithCovariates} assumes conditional independence based on the covariates.  In other words, given the information provided by the covariates, the probability of capture on one list is unaffected by another list.  If the assumption does not hold, it may lead to biased parameter estimates.  One reason the conditional independence may be violated is because the capture probabilities upon a list are directly related to the probability of being on another list, i.e., the assumption of list dependency.  This may occur if, for example, one list uses another list as a reference or data is shared between various documentation projects \citep{manrique-vallier_capture-recapture_2020}.  This would lead to heavy positive dependence between these two lists.  While this is a serious issue, we assume the lists used in the analysis are collected independently.

A second reason conditional independence may be violated is that underlying heterogeneity exists within the population that is not fully accounted for by covariates. Recall, the example cited in subsection \ref{sec:earlyapproachlitreview} of individual heterogeneity masquerading as list dependency in the study analyzing extrajudicial killings during the Guatemalan Civil War \citep{ball_making_2000}.  Researchers found that people who were part of Catholic religious communities were more likely to trust Catholic researchers with their stories than with NGO researchers associated with the political left.  Similarly, people located in areas associated with the rebel groups were more likely to do the opposite.  If this trait is unobserved and not taken into account, it will result in biased $\boldsymbol{\beta_j}$ coefficients.  Further, because of the biased coefficients, the probabilities of capture and the estimate for the population size will be biased as well (see section \ref{Sec:simulations}).

\subsubsection{Proposed Extension 2: Modelling the Unobserved Heterogeneity with Latent Classes}

We view the problem of unobserved heterogeneity through the lens of a missing covariates problem.  While there are multiple ways one could implement additional heterogeneity, we choose to add an indicator vector, $\boldsymbol{\omega_i}$, that indicates membership to one of $H_\omega$ latent groups with probability, $\boldsymbol{\phi_\omega}\sim \text{Dirichlet}(\boldsymbol{\alpha_\omega})$.  For simplicity, assume a hyperparameter specification with each value assigned the same value, $\alpha_\omega$.  Larger values of this hyperparameter put more weight on the prior and less on the data. 

This leads to three new types of parameters to sample: $\boldsymbol{\omega_i}$, $\boldsymbol{\phi_\omega}$, and  $\boldsymbol{\beta_\omega}$.  The model is constructed such that each latent group has an additional intercept affecting the probability of capture on each list.  \autoref{eqn:sigmoidfunc} then becomes

\begin{equation}
\label{eqn:sigmoidfunclatentvariable}
\lambda_{ij}=\sigma(\boldsymbol{x_i}^T\boldsymbol{\beta_j} + \boldsymbol{\omega_i}^T\boldsymbol{\beta_\omega}) = \frac{1}{1+e^{-(\boldsymbol{x_i}^T\boldsymbol{\beta_j}+\boldsymbol{\omega_i}^T\boldsymbol{\beta_\omega}))}},
\end{equation}

\subsubsection{Proposed Extension 2: Updating the Estimation}

Since we have three new parameters: $\boldsymbol{\omega_i}$, $\boldsymbol{\phi_\omega}$, and $\boldsymbol{\beta_\omega}$; we might expect to need just three new sampling methods. Unfortunately, complications once again arise from the missing covariates.  If the individual is observed, the latent group membership, $\boldsymbol{\omega_i}$, can be sampled with corresponding discrete probability,

\begin{equation}
\label{eqn:latentvariableomega}
p(\boldsymbol{\omega_i}|\boldsymbol{\phi_\omega},N,\mathcal{Y},\boldsymbol{\beta},\boldsymbol{X}) \propto \phi_\omega\prod_{j=1}^J\lambda_{ij}^{y_{ij}}(1-\lambda_{ij})^{1-y_{ij}}.
\end{equation}

For the individuals that are not observed, we draw the latent class membership during the missing covariate imputation stage. Recall, because of the complications mentioned in subsection \ref{sec:estimationBLRCRMCMC}, the Gibbs sampler requires $N$ and $\mathcal{X}_{mis}$ to be sampled simultaneously.  In order to implement the sampling procedure of the missing covariates, $\mathcal{X}_{mis}$, the latent class membership, $\boldsymbol{\omega_i}$ of each unobserved individual must be drawn initially as well from its subpopulation with probability $\boldsymbol{\phi_\omega}$.

The $\boldsymbol{\phi_\omega}$ are sampled according to,

\begin{equation}
\label{eqn:latentvariablePHIomega}
\boldsymbol{\phi_\omega} \sim \text{Dirichlet}(\alpha_\omega + n_{\omega=1}, \alpha_\omega+n_{\omega=2}, ..., \alpha_\omega+n_{\omega={H_\omega}}),
\end{equation}

where $n_{\omega}$ is the number of individuals belonging to each latent class membership and $\alpha_\omega$ is a hyperparameter which can be thought of as a prior sample size. We set $\alpha_\omega=1$. Lastly, the additional coefficient vector, $\boldsymbol{\beta_\omega}$, can be sampled in the same manner and simultaneously with the other coefficients, $\boldsymbol{\beta_j}$, when conditioned on $\boldsymbol{\phi_\omega}$. 

\subsubsection{Future Work: Implementing Stick-Breaking Priors for Latent Classes}

The current setup uses a finite number of latent classes with a prior specification of a Dirichlet($1/H_\omega$,...,$1/H_\omega$).While it may be reasonable in some cases to know the number of latent classes, it may be advantageous to utilize the stick-breaking prior. Of course, with a sufficiently large $H_\omega$ the current construction will approximate the solution under the stick-breaking prior.  Nevertheless, the current construction uses the concentration parameter, $\alpha_\omega$, as a hyperparameter.  Adding some flexibility by placing a prior on $\alpha_\omega$ could prove beneficial.

