---
title: ''
output: pdf_document
---

\newpage
\section{Introduction}
\label{sec:Introduction}

Capture-Recapture (CR) refers to a series of methods that are used to estimate the size of a population from at least two incomplete, matched lists.  While one could simply count the number of unique names between the lists, this would provide only a lower bound estimate of the population size.  Presumably, there are individuals who were not captured in any of the lists.  CR methods use assumptions along with patterns in the data to create estimates for how many individuals were missed and therefore inherently the size of the total population.

Most early applications of capture-recapture, also called mark and recapture, were in the context of animal populations where a number of animals were initially captured, marked or tagged, and then released.  This was followed up with another capturing occasion where animals were captured and checked for a marking. A CR dataset is then a listing of each unique animal's capture pattern after all sampling occasions have taken place. CR methods have been used in a wide array of additional subject areas including ecology \citep{henderson_ecological_2016}, epidemiology \citep{goldberg_estimation_1978,baker_simple_1990}, U.S. Census adjustments \citep{darroch_three-sample_1993}, and estimating the number of pages on the internet \citep{lawrence_searching_1998,khabsa_number_2014}. Of particular interest to this dissertation is the application of this methodology to human populations, which are sometimes referred to as multiple systems estimation (MSE). Lists of subjects may be collected by various institutions including hospitals, government agencies, or other non-governmental organizations but are left incomplete due to lack of resources, mistakes/omissions, or just the inability to obtain such information. These lists can then be combined and constructed to form a dataset for CR. For example, \cite{zwane_population_2005} attempts to determine the number of Dutch children born with a neural tube defect (NTD) in the year 2000 by analyzing three national databases tracking these occurrences. For multiple reasons including risk assessment of the pregnancy and omissions, not all children with NTDs are reported to each database. Another example is the counting of casualties from various conflicts including Colombia \citep{guberek_count_2010,manriquevallier_bayesian_2016}, Guatemala \citep{ball_making_2000,ball_statistics_2018}, Kosovo \citep{ball_killings_2002,manriquevallier_bayesian_2016}, Peru \citep{ball_estimate_2003}, and many others. Casualty counts by a reporting agency may only be partially collected because of non-cooperation from victims due to lack of trust, danger posed to data collectors, and/or destroyed
infrastructure \citep{manrique-vallier_capture-recapture_2020}.  

CR methods often come with many assumptions including a closed population, independence between lists, and homogeneity in the capture probability between individuals.  In particular, the aim of the dissertation is to extend methods that target the homogeneity assumption, the requirement that all individuals have the same probability of capture on each list regardless of any personal attributes.  While this may be a palatable assumption for some animal populations, this is unlikely with human populations. Different characteristics like age or social status may influence the probability of their capture. If data is present that can fully explain the heterogeneity, one could incorporate this by stratifying before applying their CR method of choice \citep{sekar_method_1949,manrique-vallier_estimating_2019}. This is only possible if the covariate is discrete or can be made discrete. It can also lead to issues of sparsity. An alternative is to include the covariates in a model like regression \citep{alho_logistic_1990,baker_simple_1990,bonner_mcmcmc_2014,king_capturerecapture_2016}. Regardless, this only addresses the observable heterogeneity and ignores heterogeneity that may exist but covariate information is missing or is not fully adequate. Some approaches have been proposed to account for unobservable heterogeneity by adapting the Rasch model \citep{darroch_three-sample_1993} or latent class memberships \citep{manriquevallier_bayesian_2016}.

This dissertation develops a fully Bayesian procedure for the CR problem that has a number of desirable characteristics:

\begin{itemize}

\item[1)] allows for multiple lists;
\item[2)] is resistant to sparsity;
\item[3)] can be informed through the use of priors;
\item[4)] uses discrete and continuous covariates to account for observable heterogeneity;
\item[5)] can also account for unobservable heterogeneity;
\item[6)] extensible;

\end{itemize}

Estimating the size of the population tends to be highly susceptible to the structure of the modeling when dealing with CR methods. Therefore, implementing covariates in an improper way or not adequately accounting for the unobservable heterogeneity can bias the inference. As a result, we propose developing a method that is fully Bayesian approach and uses the full likelihood as suggested by \cite{pollock_use_2002}. We begin by developing a framework for CR that incorporates covariates, a framework that for all intents and purposes is identical to the complete likelihood specification in  \citep{king_capturerecapture_2016}. Using this framework, we specify a model that uses conditionally independent logistic regressions which we term the Bayesian Logistic Regression Capture-Recapture (BLRCR) model. 

While the BLRCR model incorporates individual covariates and thus accounts for observable heterogeneity, it has a few shortcomings which are addressed in subsequent sections. 

\begin{list}{}{}
\item[1)] Since covariates are missing at least for the unobserved individuals, the use of a full likelihood approach requires the specification of a distribution for the covariates. As we will see in Section \ref{Sec:selectcovariates}, misspecifying the distribution can lead to incorrect inference. Like previous approaches, we apply a normal distribution; however, we propose a new method of using non-parametric approaches to the covariates such as an infinite mixture of normal distributions.

\item[2)] Unobservable heterogeneity can bias the inference, and hence we need a way to account for it. From our perspective, we view the idea of unobservable heterogeneity as an issue of omitted covariates. We borrow the idea of individuals belonging to latent classes impacts the probability of capture\citep{manriquevallier_bayesian_2016}, but implement it in the regression procedure through an additional intercept term. 

\item[3)] Determining which covariates to include and how each covariate should be included in the regression will ultimately impact the inference. There are multiple ways to account for this issue, but we explore it through the lens of variable selection.

\end{list}

The dissertation proceeds as follows: Section \ref{Sec:litreview} partially reviews the relevant capture-recapture literature.  Section \ref{sec:CRwithCovariates} details the BLRCR model along with the three extensions described above. This includes the derivation of the posterior and a Markov Chain Monte Carlo (MCMC) estimation procedure. Section \ref{sec:simulationanalysis} contains an analysis of the procedure using a series of simulations. Section \ref{Sec:example1} looks at Example 1. Section \ref{Sec:example2} looks at Example 2.  Section \ref{Sec:Conclusion} concludes with a summary of the dissertation and future directions of work in this area.






